#!name=Alight Motion Pro
#!desc=Alight Motion Pro

[Script]
alightmotion = type=http-response,script-path=https://raw.githubusercontent.com/sbunkov/shadowrocket-configuration/main/scripts/alightmotion.js,pattern=^https:\/\/us-central1-alight-creative\.cloudfunctions\.net\/getAccountStatusAndLicenses,max-size=131072,requires-body=true,timeout=10,script-update-interval=0,enable=true

[MITM]
hostname = %APPEND% us-central1-alight-creative.cloudfunctions.net
