#!name=CapCut Pro
#!desc=CapCut Pro

[Script]
capcut_pro = type=http-response,pattern=^https:\/\/api\.revenuecat\.com\/v1\/subscribers\/.*,requires-body=true,max-size=-1,script-path=https://raw.githubusercontent.com/sbunkov/shadowrocket-configuration/main/scripts/capcut.js

capcut_header_cleanup = type=http-request,pattern=^https:\/\/api\.revenuecat\.com\/v1\/(receipts|subscribers),script-path=https://raw.githubusercontent.com/duxng9324/CapCutPro/main/deleteHeader.js,timeout=60

[MITM]
hostname = %APPEND% api.revenuecat.com,capcut.net,*.capcut.net,*.bytedance.com
