# REPOSITORY: https://github.com/sbunkov/shadowrocket-configuration
# URL: https://raw.githubusercontent.com/sbunkov/shadowrocket-configuration/refs/heads/main/modules/reddit.module
# UPDATED: 2026-05-02
#!name=Reddit Ad Block
#!desc=Reddit Ad Blocker

[Script]
reddit=type=http-response,pattern=^https?:\/\/gql-fed\.reddit\.com\/$,requires-body=1,max-size=0,script-path=https://raw.githubusercontent.com/sbunkov/shadowrocket-configuration/main/scripts/reddit.js

[MITM]
hostname = %APPEND% gql-fed.reddit.com
