#!url=https://raw.githubusercontent.com/sbunkov/shadowrocket-configuration/main/modules/soundcloud.module
#!name=SoundCloudGo+
#!desc=SoundCloudGo+

[Script]
SoundCloudGo+=type=http-response,pattern=https://api-mobile.soundcloud.com/configuration/ios,requires-body=1,script-path=https://raw.githubusercontent.com/sbunkov/shadowrocket-configuration/main/scripts/soundcloud.js

[MITM]
hostname= %APPEND% api-mobile.soundcloud.com
