#!name=SoundCloud Go+
#!desc=SoundCloud Go+

[Script]
soundcloudgo = type=http-response,pattern=^https:\/\/api-mobile\.soundcloud\.com\/configuration\/ios,max-size=131072,requires-body=true,timeout=10,script-update-interval=0,enable=true,script-path=https://raw.githubusercontent.com/sbunkov/shadowrocket-configuration/main/scripts/soundcloud.js

[MITM]
hostname = %APPEND% api-mobile.soundcloud.com
