#!name=Spotify Premium
#!desc=Spotify Premium
# Unlocks part of the premium features. It’s recommended to login again. Cannot set high-quality audio.
# 1. On the search page — playlists/songs can be switched and played fully.
# 2. In the music library — liked songs can be switched and played fully.

[MITM]
hostname = %APPEND% spclient.wg.spotify.com

[Script]
spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/sbunkov/shadowrocket-configuration/main/scripts/spotify.js,script-update-interval=0
