#!name=Spotify
#!desc=Partially unlocks premium
# 2024.05.27 Partially unlocks premium, sound quality cannot be set to super high (we recommend opening the script after logging in, restarting the app and waiting for the script to take effect)
# Repository address: https://github.com/app2smile/rules
# Function: 1. Removes ads 2. Shows artist/album list normally 3. Removes random play

[Header Rewrite]
# if-none-match returns code 304
http-request ^https:\/\/spclient\.wg\.spotify\.com\/user-customization-service\/v1\/customize$ header-del if-none-match

[MITM]
hostname = %APPEND% spclient.wg.spotify.com

[Script]
spotify-json = type=http-request,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(artistview\/v1\/artist|album-entity-view\/v2\/album)\/,requires-body=0,script-path=https://raw.githubusercontent.com/sbunkov/shadowrocket-configuration/refs/heads/main/modules/spotify-json.js
spotify-proto = type=http-response,pattern=^https:\/\/spclient\.wg\.spotify\.com\/(bootstrap\/v1\/bootstrap|user-customization-service\/v1\/customize)$,requires-body=1,binary-body-mode=1,max-size=0,script-path=https://raw.githubusercontent.com/sbunkov/shadowrocket-configuration/refs/heads/main/modules/spotify-proto.js,script-update-interval=0
