#!name=VivaCut Pro
#!desc=VivaCut Pro

[Script]
vivacut = type=http-response,script-path=https://raw.githubusercontent.com/sbunkov/shadowrocket-configuration/main/scripts/vivacut.js,pattern=^https:\/\/.*\.vivacut\.com\/.*(subscription|license|pro|vip|premium|status|account).*$,max-size=131072,requires-body=true,timeout=10,script-update-interval=0,enable=true

[MITM]
hostname = %APPEND% *.vivacut.com
