# REPOSITORY: https://github.com/sbunkov/shadowrocket-configuration
# URL: https://raw.githubusercontent.com/sbunkov/shadowrocket-configuration/refs/heads/main/modules/vlogstar.module
# UPDATED: 2026-05-02
#!name=VlogStar Pro
#!desc=VlogStar Pro

[Script]
vlogstar = type=http-response,script-path=https://raw.githubusercontent.com/sbunkov/shadowrocket-configuration/main/scripts/vlogstar.js,pattern=^https:\/\/buy\.itunes\.apple\.com\/verifyReceipt,requires-body=true,timeout=10,script-update-interval=0,enable=true,max-size=131072

[MITM]
hostname = %APPEND% buy.itunes.apple.com
