#!name=YouTube Premium
#!desc=YouTube Ad Full Blocker With PIP Player
#!arguments=blockUpload:true,blockImmersive:true,captionLang:off,lyricLang:ru,scriptExecutionEngine:auto,debug:false,blockShorts:true

[Rule]
AND,((DOMAIN-SUFFIX,googlevideo.com),(PROTOCOL,UDP)),REJECT
AND,((DOMAIN,youtubei.googleapis.com),(PROTOCOL,UDP)),REJECT

[URL Rewrite]
(^https?:\/\/.+\.googlevideo\.com\/.+)(&ctier=[A-Z])(&.+) $1$3 302
^https?:\/\/[\w-]+\.googlevideo\.com\/initplayback.+&oad _ REJECT-IMG
https?:\/\/.+\.googlevideo\.com\/.+&oad reject header
https?:\/\/.+\.googlevideo\.com\/ptracking\?pltype=adhost reject header
https?:\/\/.+\.youtube\.com\/api\/stats\/.+adformat reject header
https?:\/\/.+\.youtube\.com\/api\/stats\/ads reject header
https?:\/\/.+\.youtube\.com\/pagead\/ reject header
https?:\/\/m\.youtube\.com\/_get_ads reject header
https?:\/\/pagead2\.googlesyndication\.com\/pagead\/ reject header
https?:\/\/s\.youtube\.com\/api\/stats\/watchtime\?adformat reject header
https?:\/\/youtubei\.googleapis\.com\/.+ad_break reject header

[Script]
youtube.request = type=http-request,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|reel\/reel_watch_sequence|get_watch),requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.response.js
youtube.response = type=http-response,pattern=^https:\/\/youtubei\.googleapis\.com\/youtubei\/v1\/(browse|next|player|search|reel\/reel_watch_sequence|guide|account\/get_setting|get_watch),requires-body=1,max-size=-1,binary-body-mode=1,script-path=https://raw.githubusercontent.com/Maasea/sgmodule/master/Script/Youtube/youtube.response.js,argument="{\"lyricLang\":\"{{null}}\",\"captionLang\":\"{{{null}}}\",\"blockUpload\":true,\"blockImmersive\":true,\"debug\":false}"

[MITM]
hostname = %APPEND% *.googlevideo.com, youtubei.googleapis.com
