# REPOSITORY: https://github.com/sbunkov/shadowrocket-configuration
# URL: https://raw.githubusercontent.com/sbunkov/shadowrocket-configuration/main/extended.conf
# UPDATED: 2026-05-02
[MITM]
ca-passphrase = Shadowrocket
enable = true
